name: Validate Conventional Commits

on:
  push:
    branches:
      - 'feature/*'
      - 'hotfix/*'
      
permissions:
  contents: read
  
jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Conventional Commits
        run : |
          echo "Checking commit message..."
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          if ! echo "$COMMIT_MESSAGE" | grep -E '^(feat|fix|chore|docs|style|refactor|perf|test|build|ci|revert|merge)(\(.+\))?: .{1,72}$'; then
            echo "Commit message does not follow Conventional Commits guidelines!"
            exit 1
          fi
