name: Validate Conventional Commits

on:
  push:
    branches:
      - 'feature/**'
      - 'hotfix/**'
      
#permissions:
#  contents: read
  
jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Conventional Commits
        uses: webiny/action-conventional-commits@v1.3.0
